USE [Broxel]
GO

IF OBJECT_ID('SPDelProspectos') IS NOT NULL
	DROP PROCEDURE [dbo].[SPDelProspectos]
GO

CREATE PROCEDURE [dbo].[SPDelProspectos] 
(	
	@piIdProspecto			INT
)
AS
DECLARE	@vcMessage	NVARCHAR(255)	=	''

SET NOCOUNT ON

	BEGIN TRAN T1

		SET @vcMessage = 'ERROR- NO SE PUDO ELIMINAR LA INFORMACIÓN DEL PROSPECTO.'

		DELETE FROM opeProspectos
			WHERE Id = @piIdProspecto
			
		IF @@ERROR <> 0  GOTO ERRORES
		
	COMMIT TRAN T1
	
	SELECT 1;
		
SET NOCOUNT OFF
	RETURN 0

ERRORES:
	IF(@@TRANCOUNT>0)
		ROLLBACK TRAN T1
	SET NOCOUNT OFF
	SET @vcMessage = @vcMessage + ISNULL(ERROR_MESSAGE(),'')
	RAISERROR(@vcMessage,10,1)
	RETURN -1
GO